import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().optional(),
  NEXTAUTH_SECRET: z.string().optional(),
  NEXTAUTH_URL: z.string().optional(),
  APP_URL: z.string().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  PINTEREST_CLIENT_ID: z.string().optional(),
  PINTEREST_CLIENT_SECRET: z.string().optional(),
  PINTEREST_REDIRECT_URI: z.string().optional(),
  PINTEREST_TOKEN_ENCRYPTION_KEY: z.string().optional(),
  PINTEREST_API_BASE_URL: z.string().optional(),
  GEMINI_API_KEY: z.string().optional(),
  CLOUDINARY_CLOUD_NAME: z.string().optional(),
  CLOUDINARY_API_KEY: z.string().optional(),
  CLOUDINARY_API_SECRET: z.string().optional(),
  REDIS_URL: z.string().optional(),
  PUBLISH_QUEUE_SECRET: z.string().optional(),
  PUBLISH_QUEUE_BATCH_SIZE: z.coerce.number().optional().default(1),
  PUBLISH_QUEUE_MAX_BATCH_SIZE: z.coerce.number().optional().default(5),
  PUBLISH_QUEUE_LOCK_TIMEOUT_MINUTES: z.coerce.number().optional().default(5),
  MAKE_WEBHOOK_URL: z.string().optional(),
  MAKE_WEBHOOK_SECRET: z.string().optional(),
  MAKE_CALLBACK_SECRET: z.string().optional(),
  CLOUDFLARE_ACCOUNT_ID: z.string().optional(),
  CLOUDFLARE_API_TOKEN: z.string().optional(),
  CLOUDFLARE_AI_BASE_URL: z.string().optional(),
  CLOUDFLARE_AI_TEXT_MODEL: z.string().optional(),
  CLOUDFLARE_AI_IMAGE_MODEL: z.string().optional(),
  CLOUDFLARE_R2_ACCOUNT_ID: z.string().optional(),
  CLOUDFLARE_R2_ACCESS_KEY_ID: z.string().optional(),
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: z.string().optional(),
  CLOUDFLARE_R2_BUCKET: z.string().optional(),
  CLOUDFLARE_R2_PUBLIC_BASE_URL: z.string().optional(),
});

export const env = envSchema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  APP_URL: process.env.APP_URL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  PINTEREST_CLIENT_ID: process.env.PINTEREST_CLIENT_ID,
  PINTEREST_CLIENT_SECRET: process.env.PINTEREST_CLIENT_SECRET,
  PINTEREST_REDIRECT_URI: process.env.PINTEREST_REDIRECT_URI,
  PINTEREST_TOKEN_ENCRYPTION_KEY: process.env.PINTEREST_TOKEN_ENCRYPTION_KEY,
  PINTEREST_API_BASE_URL: process.env.PINTEREST_API_BASE_URL,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  REDIS_URL: process.env.REDIS_URL,
  PUBLISH_QUEUE_SECRET: process.env.PUBLISH_QUEUE_SECRET,
  PUBLISH_QUEUE_BATCH_SIZE: process.env.PUBLISH_QUEUE_BATCH_SIZE,
  PUBLISH_QUEUE_MAX_BATCH_SIZE: process.env.PUBLISH_QUEUE_MAX_BATCH_SIZE,
  PUBLISH_QUEUE_LOCK_TIMEOUT_MINUTES: process.env.PUBLISH_QUEUE_LOCK_TIMEOUT_MINUTES,
  MAKE_WEBHOOK_URL: process.env.MAKE_WEBHOOK_URL,
  MAKE_WEBHOOK_SECRET: process.env.MAKE_WEBHOOK_SECRET,
  MAKE_CALLBACK_SECRET: process.env.MAKE_CALLBACK_SECRET,
  CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
  CLOUDFLARE_AI_BASE_URL: process.env.CLOUDFLARE_AI_BASE_URL,
  CLOUDFLARE_AI_TEXT_MODEL: process.env.CLOUDFLARE_AI_TEXT_MODEL,
  CLOUDFLARE_AI_IMAGE_MODEL: process.env.CLOUDFLARE_AI_IMAGE_MODEL,
  CLOUDFLARE_R2_ACCOUNT_ID: process.env.CLOUDFLARE_R2_ACCOUNT_ID,
  CLOUDFLARE_R2_ACCESS_KEY_ID: process.env.CLOUDFLARE_R2_ACCESS_KEY_ID,
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY,
  CLOUDFLARE_R2_BUCKET: process.env.CLOUDFLARE_R2_BUCKET,
  CLOUDFLARE_R2_PUBLIC_BASE_URL: process.env.CLOUDFLARE_R2_PUBLIC_BASE_URL,
});
